name: Open-WebUI with Ngrok

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-open-webui:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python 3.11
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.0'

      # Step 3: Install any necessary dependencies for Open-WebUI
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install open-webui

      # Step 4: Start the Open-WebUI server
      - name: Start Open-WebUI server
        run: |
          open-webui serve &
        env:
          PORT: 8080

      # Step 5: Install and configure ngrok
      - name: Install and configure ngrok
        run: |
          wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
          unzip ngrok-stable-linux-amd64.zip
          ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
          nohup ./ngrok http 8080 &

      # Step 6: Wait for ngrok to start and display the public URL
      - name: Display ngrok URL
        run: |
          sleep 5  # Give ngrok some time to start
          curl --silent http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url'

      # Step 7: Keep the job running to allow server access
      - name: Keep workflow alive
        run: sleep 1d
