name: Open-WebUI with Localhost.run

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-open-webui:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python 3.11
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.0'

      # Step 3: Install any necessary dependencies for Open-WebUI
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install open-webui

      # Step 4: Start the Open-WebUI server
      - name: Start Open-WebUI server
        run: |
          open-webui serve & 
        env:
          PORT: 8080

      # Step 5: Start localhost.run tunnel
      - name: Start localhost.run tunnel
        run: |
          ssh -o StrictHostKeyChecking=no -R 80:localhost:8080 localhost.run &
          sleep 5  # Give localhost.run time to start

      # Step 6: Display the public URL for localhost.run
      - name: Display localhost.run URL
        run: |
          ssh -o StrictHostKeyChecking=no -R 80:localhost:8080 localhost.run 2>&1 | grep -o 'https://.*'

      # Step 7: Keep the job running to allow server access
      - name: Keep workflow alive
        run: sleep 1d
